### ISSUE TITLE
博客的模板

### ISSUE THREAD

**Issue by autodataming** [Andrew-liu/my_blog_tutorial#12]
你好，请问博客的模板是下载的，还是从头设计的？
如果是下载，请问是哪里下载

**Comment by autodataming** [comment]
http://andrew-liu.gitbooks.io/django-blog/content/index.html

我想设计这样的模板，但是没有逻辑思路。

**Comment by Andrew-liu** [comment]
@autodataming  学习CSS, 然后再设计, 博客使用的是hexo. 主题是别人的...

**Comment by autodataming** [comment]
https://github.com/Andrew-liu/my_blog_tutorial/blob/master/templates/base.html

和http://andrewliu.in/
好像没有更新。 base.html

 <nav class="nav">
 <ul class="nav-list">
<li class="nav-item">
<a class="button-success pure-button" href="/">主页</a>
</li>
<li class="nav-item">
<a class="button-success pure-button" href="{% url 'archives' %}">归档</a>
</li>
<li class="nav-item">
<a class="pure-button" href="https://github.com/Andrew-liu/my_blog_tutorial">Github</a>
</li>
<li class="nav-item">
<a class="button-error pure-button" href="http://weibo.com/dinosaurliu">Weibo</a>
</li>
<li class="nav-item">
<a class="button-success pure-button" href="/">专题</a>
</li>
<li>

<form class="pure-form" action="/search/" method="get">
<input class="pure-input-3-3" type="text" name="s" placeholder="search">
</form>

</li>
<li class="nav-item">
<a class="button-success pure-button" href="{% url 'about_me' %}">About Me</a>
</li>
<li class="nav-item">
<a class="button-success pure-button" href="{% url 'RSS' %}">RSS</a>
</li>
</ul>
</nav>

**Comment by zjwangmin** [comment]
请问你的blog不是使用你的django那个教程的模板吧？能不能告知，谢谢！

**Comment by Andrew-liu** [comment]
@zjwangmin  不是, 之前没有服务器, 所以没法部署, 用了Github Pages
