### ISSUE TITLE
Django 1.8环境下文中的配置文件有些内容需要修改

### ISSUE THREAD

**Issue by wizard1990** [Andrew-liu/my_blog_tutorial#13]
设置bootstrap以及本地template路径的时候 settings.py中的相关内容应该是：
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_PATH],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.contrib.auth.context_processors.auth',
                'django.template.context_processors.debug',
                'django.template.context_processors.i18n',
                'django.template.context_processors.media',
                'django.template.context_processors.static',
                'django.template.context_processors.tz',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.request'
            ],
        },
    },
]
原文中是：
from django.conf import global_settings
TEMPLATE_CONTEXT_PROCESSORS = global_settings.TEMPLATE_CONTEXT_PROCESSORS + (
    'django.core.context_processors.request',
)
在Django 1.8下会报错

**Comment by Andrew-liu** [comment]
@wizard1990  不好意思, 本文已经声明了基于的版本是1.7.1 并没有做1.8的适配

**Comment by OrangePJ** [comment]
@wizard1990 兄弟我用的 1.8 版本按照你的配置来也不行啊，提示找不到 `'DIRS': [TEMPLATE_PATH],`
