### ISSUE TITLE
你的教程只是教了怎么从数据库读数据到页面，而没有教怎么从页面写数据到数据库

### ISSUE THREAD

**Issue by ronyland** [Andrew-liu/my_blog_tutorial#27]

**Comment by Andrew-liu** [comment]
http://andrewliu.in/2014/12/26/Django%E6%90%AD%E5%BB%BA%E7%AE%80%E6%98%93%E5%8D%9A%E5%AE%A2%E6%95%99%E7%A8%8B-%E5%9B%9B-Models/

写数据库就是用户post提交数据，然后存到数据库的操作（在数据库增加一行数据就好了）
