### ISSUE TITLE
感谢分享，但是gitbook文章中有一处贴代码的小错误

### ISSUE THREAD

**Issue by hylarucoder** [Andrew-liu/my_blog_tutorial#4]
在这一块 在my_blog/my_blog/view下新建归档view  你把代码贴成了def search_tag(request, tag) :

http://andrew-liu.gitbooks.io/django-blog/content/gui_68632c_aboutme_he_biao_qian_fen_lei.html

**Comment by Andrew-liu** [comment]
`非常感谢纠结, 已经进行了修改`
