### ISSUE TITLE
激活虚拟环境时出现问题

### ISSUE THREAD

**Issue by raighnew** [Andrew-liu/my_blog_tutorial#8]
提示：Not overwriting existing python script ENV3.4/bin/python (you must use ENV3.4/bin/python3.4)

**Comment by Andrew-liu** [comment]
我们环境不同, 所以对于你电脑上的Python3环境位置我并不清楚, 你可以查看自己PC上python3位置

**Comment by raighnew** [comment]
osx10.10.3，安装了python3.4.3，需要把3.4.3设为系统默认python版本吗？

发自翁浩

**Comment by Andrew-liu** [comment]
不需要, 直接通过virtulenv指定python的版本, 可以查看我以前写的virtualenv用法  [Virtualenv简明教程](http://andrewliu.tk/2014/12/08/Virtualenv%E7%AE%80%E6%98%8E%E6%95%99%E7%A8%8B/)
