### ISSUE TITLE
询问能否 PR

### ISSUE THREAD

**Issue by lsdlab** [Andrew-liu/my_blog_tutorial#9]
我是看了你的教程做了一个博客，增加了标签功能，RSS 好像有些问题，请问我能不能添加代码？我自己做了之后也在 VPS 上部署上线了，也写了博客，能不能将这个教程再丰富一些？

**Comment by Andrew-liu** [comment]
可以

**Comment by Andrew-liu** [comment]
标签功能我之前已经做过了, RSS貌似没有问题的, 我都测试过, 可能是你环境问题, 不过还是感谢你的RP

**Comment by lsdlab** [comment]
@Andrew-liu  标签和分类，这两个在代码和教程里面的都是混淆的

**Comment by Andrew-liu** [comment]
@lsdlab 我把标签和分类当作一样东西处理的, 各人有各人的处理方式吧

**Comment by lsdlab** [comment]
OK

**Comment by Andrew-liu** [comment]
@lsdlab  还是要感谢你, 希望我的文章对你有帮助吧

**Comment by lsdlab** [comment]
@Andrew-liu 也很感谢你，虽然是个小项目，但也学习了很多，从零开始到增加功能，修 bug，到部署上线，很有成就感。
